version: "2"
services:
  githubservice:
    build:
      context: ./github-service
    environment:
      APP_PORT: 8080
      ALL_REPOS_LIST_URL: https://api.github.com/users/Major98113/repos
    ports:
      - '8080:8080'